USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/kobo/macallan/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := tegra
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a15
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := macallan

BOARD_KERNEL_CMDLINE := 

BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# Try to build the kernel
TARGET_KERNEL_SOURCE := kernel/kobo/Kobo-arc10-HD-kernel

# Partition
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608 # 8M
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 8388608 # 8 M
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 792641536 # 756M , APP - mmcblk0p4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 13971501056 # 13.01G , UDA - mmcblk0p9

BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 528424960 # 504M , CAC - mmcblk0p5

BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/kobo/macallan/kernel

TARGET_KERNEL_CONFIG := koboarc10hd_defconfig

BOARD_HAS_NO_SELECT_BUTTON := true
